# Generated by Django 4.2.25 on 2025-11-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('isi', models.TextField()),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='berita_app.berita')),
            ],
        ),
    ]
