# Generated by Django 4.2.24 on 2025-10-03 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=255)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('link_aplikasi', models.URLField(blank=True, help_text='Link eksternal ke halaman lamaran.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nim', models.CharField(max_length=11, unique=True)),
                ('program_studi', models.CharField(choices=[('business', 'Business'), ('financial_technology', 'Financial Technology'), ('international_marketing', 'International Marketing'), ('finance_and_banking', 'Finance and Banking'), ('branding', 'Branding'), ('hospitality_busines', 'Hospitality Business'), ('event', 'Event'), ('business_economics', 'Business Economics'), ('accounting', 'Accounting'), ('artificial_intelligence_and_robotics', 'Artificial Intelligence and Robotics'), ('digital_business_technology', 'Digital Business Technology'), ('food_business_technology', 'Food Business Technology'), ('business_mathematics', 'Business Mathematics'), ('product_design_innovation', 'Product Design Innovation'), ('energy_business_technology', 'Energy Business Technology'), ('international_business_law', 'International Business Law')], max_length=100)),
                ('angkatan', models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')])),
                ('jenis_kelamin', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('email_outlook', models.EmailField(max_length=254, unique=True)),
                ('kontak_whatsapp', models.CharField(max_length=15)),
                ('bukti_konsultasi', models.FileField(upload_to='dokumen/konsultasi/')),
                ('sptjm', models.FileField(upload_to='dokumen/sptjm/')),
                ('cv', models.FileField(upload_to='dokumen/cv/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='dokumen/portfolio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('posisi', models.CharField(max_length=100)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('alamat_perusahaan', models.TextField()),
                ('bidang_usaha', models.CharField(choices=[('teknologi', 'Teknologi Informasi'), ('finance', 'Keuangan & Perbankan'), ('manufacturing', 'Manufaktur'), ('retail', 'Retail & E-commerce'), ('consulting', 'Konsultasi Bisnis'), ('fmcg', 'FMCG'), ('healthcare', 'Kesehatan'), ('education', 'Pendidikan'), ('other', 'Lainnya')], max_length=50)),
                ('nama_supervisor', models.CharField(max_length=255)),
                ('email_supervisor', models.EmailField(max_length=254)),
                ('kontak_supervisor', models.CharField(blank=True, max_length=20, null=True)),
                ('bukti_konfirmasi', models.FileField(upload_to='dokumen/konfirmasi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magang', to='coop.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_perusahaan', models.TextField()),
                ('jobdesk', models.TextField()),
                ('suasana_kerja', models.TextField()),
                ('manfaat_perkuliahan', models.TextField()),
                ('kesenjangan_pembelajaran', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('magang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='coop.magang')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaporanAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesimpulan_magang', models.TextField(help_text='Ringkasan dan kesimpulan dari seluruh pengalaman magang Anda.')),
                ('dokumen_laporan_akhir', models.FileField(upload_to='dokumen/laporan_akhir/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('magang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_akhir', to='coop.magang')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluasiSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('penilaian_kinerja', models.TextField(blank=True, null=True)),
                ('penilaian_komunikasi', models.TextField(blank=True, null=True)),
                ('masukan_tambahan', models.TextField(blank=True, null=True)),
                ('sudah_diisi', models.BooleanField(default=False)),
                ('tanggal_diisi', models.DateTimeField(blank=True, null=True)),
                ('magang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi', to='coop.magang')),
            ],
        ),
    ]
