# Generated by Django 4.2.24 on 2025-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magang',
            name='nilai_akhir',
            field=models.CharField(blank=True, help_text='Nilai akhir yang diinput oleh admin/dosen (Contoh: A, B+, C)', max_length=2, null=True),
        ),
    ]
